### ISSUE TITLE
Support for Windows 11

### ISSUE THREAD

**Issue by gtusr** [Fajar-RahmadJaya/KeyTik#8]
Interception driver is not officially supported under Windows 11.

Does KeyTik offer a workaround?

**Comment by Fajar-RahmadJaya** [comment]
Hi @gtusr !! 
Sorry for the late response.

> Interception driver is not officially supported under Windows 11.

   It's my first time hearing this. I myself is using windows 11 to test and build it. I suppose that's why when i try to install it, there is no Interception Driver on device manager but i think it's installed because when i try to install again without uninstall it, it show error. But overall, it's still working fine on my device using windows 11.  It might be because AutoHotkey wrapper, [AutoHotkey Interception by evilC](https://github.com/evilC/AutoHotInterception) is already cover it, but it just my guess. 


   If you don't mind, can you help me test it out using your device on windows 11?. 
Is it working or not. And if not, can you give me the detailed error?
Thank you!
